on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # trigger on semver tags pushes like v1.0.0, v1.0.0-beta1, etc.

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [alpine, debian]
        arch: [amd64, arm64]

    steps:
      - name: Generate application token
        id: generate-token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Fetch pogocache artifacts
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          repository: 'pogocache/pogocache'
          tag: ${{ github.ref_name }}
          tarBall: true
          extract: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ vars.GH_APP_ID }}
          password: ${{ steps.generate-token.outputs.token }}

      - name: Build and push Docker images
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/pogocache:latest,ghcr.io/${{ github.repository_owner }}/pogocache:${{ github.ref_name }}
          platforms: linux/${{ matrix.arch }}
          file: Dockerfile.${{ matrix.os }}.${{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
